fix: fixed typo in actions

diff --git a/.github/workflows/snake.yaml b/.github/workflows/snake.yaml
--- a/.github/workflows/snake.yaml
+++ b/.github/workflows/snake.yaml
@@ -33,10 +33,10 @@ jobs:
           palette: github-light
 
       - name: Verify snake-dark.svg exists
-        run: test -f dist/dark-snake.svg && echo "Dark SVG generated!" || (echo "Dark SVG not found!" && exit 1)
+        run: test -f dist/snake-dark.svg && echo "Dark SVG generated!" || (echo "Dark SVG not found!" && exit 1)
 
       - name: Verify snake-light.svg exists
-        run: test -f dist/light-snake.svg && echo "Light SVG generated!" || (echo "Light SVG not found!" && exit 1)
+        run: test -f dist/snake-light.svg && echo "Light SVG generated!" || (echo "Light SVG not found!" && exit 1)
 
       - name: Push snake SVGs to output branch
         uses: crazy-max/ghaction-github-pages@v3.1.0
